### ISSUE TITLE
model parameters and inference time

### ISSUE THREAD

**Issue by huiyang0613** [luzzou/6D-ViT#3]
@luzzou Dear author：
Thank you so much for sharing! I sincerely hope that you will publish the model parameters and inference time of 6DViT.

**Comment by luzzou** [comment]
> ti

Hi~ Thank you for your interest! You can look up the results in the last row of TABLE VII.

**Comment by huiyang0613** [comment]
> > ti
> 
> Hi~ Thank you for your interest! You can look up the results in the last row of TABLE VII.

![捕获](https://user-images.githubusercontent.com/115716973/233885962-87fd7c00-1329-406f-906e-b6fdc6e96605.PNG)

I carefully checked the contents of Table VII and found no data on model parameters and inference time~

**Comment by luzzou** [comment]
> > > ti
> > 
> > 
> > Hi~ Thank you for your interest! You can look up the results in the last row of TABLE VII.
> 
> ![捕获](https://user-images.githubusercontent.com/115716973/233885962-87fd7c00-1329-406f-906e-b6fdc6e96605.PNG)
> 
> I carefully checked the contents of Table VII and found no data on model parameters and inference time~

This is the latest version,which includes more results :) https://ieeexplore.ieee.org/document/9933183

**Comment by huiyang0613** [comment]
> > > > ti
> > > 
> > > 
> > > Hi~ Thank you for your interest! You can look up the results in the last row of TABLE VII.
> > 
> > 
> > ![捕获](https://user-images.githubusercontent.com/115716973/233885962-87fd7c00-1329-406f-906e-b6fdc6e96605.PNG)
> > I carefully checked the contents of Table VII and found no data on model parameters and inference time~
> 
> This is the latest version,which includes more results :) https://ieeexplore.ieee.org/document/9933183

Thank you for your patient answer， Looking forward to sharing more wonderful work in the future~
