### ISSUE TITLE
Reproduce the 3DIoU Metrics on NOCS-REAL

### ISSUE THREAD

**Issue by CNJianLiu** [luzzou/6D-ViT#4]
Hi, nice to see such a great job! But there is a small mistake in the original evaluation source code of NOCS. The evaluation source code after revision is given [here](https://github.com/swords123/SSC-6D/blob/4896efd4777c0a36e68ee6ea985f322375c58a38/eval/utils.py#L115). Could you recalculate the 3DIoU(50, 75) metrics on NOCS-REAL? Since this is very important to us, we'd really like you to retest it, even though it might take you some time:).

**Comment by luzzou** [comment]
> Hi, nice to see such a great job! But there is a small mistake in the original evaluation source code of NOCS. The evaluation source code after revision is given [here](https://github.com/swords123/SSC-6D/blob/4896efd4777c0a36e68ee6ea985f322375c58a38/eval/utils.py#L115). Could you recalculate the 3DIoU(50, 75) metrics on NOCS-REAL? Since this is very important to us, we'd really like you to retest it, even though it might take you some time:).

Thank you very much for your interest! I have recalculated all metrics using the updated calculation method, and I have placed the evaluation logs at the following link: [[link](https://drive.google.com/drive/folders/1nfELPlLWQwbGd4U5rC-l6wll7dkE4DEL?usp=share_link)]. I hope this will be helpful for you :)

**Comment by CNJianLiu** [comment]
> > Hi, nice to see such a great job! But there is a small mistake in the original evaluation source code of NOCS. The evaluation source code after revision is given [here](https://github.com/swords123/SSC-6D/blob/4896efd4777c0a36e68ee6ea985f322375c58a38/eval/utils.py#L115). Could you recalculate the 3DIoU(50, 75) metrics on NOCS-REAL? Since this is very important to us, we'd really like you to retest it, even though it might take you some time:).
> 
> Thank you very much for your interest! I have recalculated all metrics using the updated calculation method, and I have placed the evaluation logs at the following link: [[link](https://drive.google.com/drive/folders/1nfELPlLWQwbGd4U5rC-l6wll7dkE4DEL?usp=share_link)]. I hope this will be helpful for you :)

Thanks, this helps me a lot :)
